In [1]:
## categorial, Dummy variables, One Hot Encoding
## 1. Using sklearn get_dummies
## 2. Using sklearn OneHotEncoder

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [3]:
df = pd.read_excel('house_extended.xlsx')

In [4]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000

In [5]:
# df.to_csv('house_extended')

In [6]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robbinsville  west windsor
0                 1             0             0
1                 1             0             0
2                 1             0             0
3                 1             0             0
4                 1             0             0
5                 0             0             1
6                 0             0             1
7                 0             0             1
8                 0             0             1
9                 0             1             0
10                0             1             0
11                0             1             0
12                0             1             0

In [7]:
df_dummies = pd.concat([df, dummies], axis = 'columns')

In [8]:
df_dummies

town  area   price  monroe township  robbinsville  west windsor
0   monroe township  2600  550000                1             0             0
1   monroe township  3000  565000                1             0             0
2   monroe township  3200  610000                1             0             0
3   monroe township  3600  680000                1             0             0
4   monroe township  4000  725000                1             0             0
5      west windsor  2600  585000                0             0             1
6      west windsor  2800  615000                0             0             1
7      west windsor  3300  650000                0             0             1
8      west windsor  3600  710000                0             0             1
9      robbinsville  2600  575000                0             1             0
10     robbinsville  2900  600000                0             1             0
11     robbinsville  3100  620000                0             1             0
12     robbinsville  3600  695000                0             1             0

In [9]:
df_dummies = df_dummies.drop(['town', 'west windsor'], axis = 'columns')

In [10]:
df_dummies

area   price  monroe township  robbinsville
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             0
6   2800  615000                0             0
7   3300  650000                0             0
8   3600  710000                0             0
9   2600  575000                0             1
10  2900  600000                0             1
11  3100  620000                0             1
12  3600  695000                0             1

In [12]:
x= df_dummies.drop('price', axis = 'columns')

In [14]:
y =df_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [16]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [17]:
model.predict([[3400, 0 , 0]])

c:\users\mecha\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [18]:
model.predict([[2800, 0, 1]])

c:\users\mecha\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [19]:
model.predict([[2800, 1, 0]])

c:\users\mecha\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565089.22812299])

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [24]:
dfle = df

In [25]:
dfle.town = le.fit_transform(dfle.town)

In [26]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [103]:
x= dfle[['town', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [104]:
y =dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

In [105]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_transformer
ct = make_column_transformer(
    (OneHotEncoder(categories = 'auto'), [0]),
    remainder = "passthrough"
)
 

In [106]:
## creating categorical column in x dataframe
x= ct.fit_transform(x)
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [107]:
x= x[:, 1:]

In [108]:
x

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [111]:
model2 = LinearRegression()
model2.fit(x,y)


LinearRegression()

In [112]:
 model2.predict([[0,1,3400]])

array([681241.6684584])

In [113]:
model2.predict([[1,0,2000]])

array([489257.68651903])

In [114]:
model2.score(x,y)

0.9573929037221873