In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('mul_house.csv')
df

Unnamed: 0     area  bedrooms   age     price
0           0   2600.0       3.0  20.0  550000.0
1           1   3000.0       4.0  15.0  565000.0
2           2   3200.0       NaN  18.0  610000.0
3           3   3600.0       3.0  30.0  595000.0
4           4   4000.0       5.0   8.0  760000.0
5           5  41000.0       6.0   8.0  810000.0

In [3]:
df

Unnamed: 0     area  bedrooms   age     price
0           0   2600.0       3.0  20.0  550000.0
1           1   3000.0       4.0  15.0  565000.0
2           2   3200.0       NaN  18.0  610000.0
3           3   3600.0       3.0  30.0  595000.0
4           4   4000.0       5.0   8.0  760000.0
5           5  41000.0       6.0   8.0  810000.0

In [4]:
df = df.drop(5)

In [5]:
df.to_csv('mul_house.csv')


In [6]:
df

Unnamed: 0    area  bedrooms   age     price
0           0  2600.0       3.0  20.0  550000.0
1           1  3000.0       4.0  15.0  565000.0
2           2  3200.0       NaN  18.0  610000.0
3           3  3600.0       3.0  30.0  595000.0
4           4  4000.0       5.0   8.0  760000.0

In [22]:
import math
df.bedrooms.median()

3.75

In [20]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [9]:
df

Unnamed: 0    area  bedrooms   age     price
0           0  2600.0       3.0  20.0  550000.0
1           1  3000.0       4.0  15.0  565000.0
2           2  3200.0       3.5  18.0  610000.0
3           3  3600.0       3.0  30.0  595000.0
4           4  4000.0       5.0   8.0  760000.0

In [10]:
df

Unnamed: 0    area  bedrooms   age     price
0           0  2600.0       3.0  20.0  550000.0
1           1  3000.0       4.0  15.0  565000.0
2           2  3200.0       3.5  18.0  610000.0
3           3  3600.0       3.0  30.0  595000.0
4           4  4000.0       5.0   8.0  760000.0

In [11]:
df_sample = {'area' : 4100, 'bedrooms' : 6, 'price' : 810000}

In [12]:
df= df.append(df_sample, ignore_index = True)

In [16]:
df.age = df.age.fillna(8)

In [23]:
df

area  bedrooms   age     price
0  2600.0       3.0  20.0  550000.0
1  3000.0       4.0  15.0  565000.0
2  3200.0       3.5  18.0  610000.0
3  3600.0       3.0  30.0  595000.0
4  4000.0       5.0   8.0  760000.0
5  4100.0       6.0   8.0  810000.0

In [18]:
model = linear_model.LinearRegression()
model.fit(df.drop('price', axis='columns'), df.price)

LinearRegression()

In [25]:
model.predict([[3000, 3, 10]])

c:\users\mecha\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([598038.61067408])

In [26]:
model.coef_

array([  110.76035614, 23256.46711536, -3238.45104247])

In [27]:
model.intercept_

228372.6513182001

In [29]:
# 110.76035614 * 3000 + 23256.46711536 * 3 - 3238.45104247*10 +model.intercept_

# 598038.6106595802

In [30]:
model.predict([[2500, 4, 5]])

c:\users\mecha\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([582107.15492938])